### ISSUE TITLE
Release ApiDOM packages to `npmjs.com`

### ISSUE THREAD

**Issue by char0n** [swagger-api/apidom#2290]
We currently release the packages to GitHub Package registry. Whoever that want's to install them, need to have GitHub account and use [PAT](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) to install the packages.

**TODO:**

- [x] remove references to https://npm.pkg.github.com/ in workflow files 
- [x] remove references to `NODE_AUTH_TOKEN` in workflow files 
- [x] remove references to `https://registry.npmjs.org` in workflow files

---

It has been decided that package names will stay the same e.g. `@swagger-api/apidom-core`, to retain consistency with [GitHub swagger-api organization](https://github.com/swagger-api) and current package names (that were being published to [GitHub Package Registry](https://github.com/orgs/swagger-api/packages?repo_name=apidom)).

**Comment by char0n** [comment]
High priority

**Comment by char0n** [comment]
0.68.1 was successfully published to npm: https://www.npmjs.com/search?q=apidom&page=0&perPage=30

**Comment by char0n** [comment]
release CD pipeline verified on [0.69.0](https://github.com/swagger-api/apidom/releases/tag/v0.69.0) release.
