### ISSUE TITLE
apidom-reference: add support for Relative JSON Pointer in OpenAPI 3.1.0 dereferencing/resolution

### ISSUE THREAD

**Issue by char0n** [swagger-api/apidom#3040]
Support for Relative JSON Pointer for ApiDOM has been implemented in https://github.com/swagger-api/apidom/issues/3030. The goal of this issue is to use the implementation inside the OpenAPI 3.1.0 dereference/resolution strategies.

Refs #3030

**TODO**:

 - [ ] implement to OpenAPI 3.1.0 dereference
 - [ ] implement to OpenAPI 3.1.0 resolution
 - [ ] implement to SwaggerClient (probably create separate ticket for this in SwaggerClient repo)

**Comment by char0n** [comment]
We can't use an Relative JSON Pointer (RJP) in a `$ref` keyword, as `$ref` takes a URI-reference, and RJPs can't be used in those.
