### ISSUE TITLE
OpenAPI 2.0 - create namespace

### ISSUE THREAD

**Issue by char0n** [swagger-api/apidom#3097]
Scope of this issue is to implement OpenAPI 2.0 namespace package.

**TODO**:

- [x] [create new empty ApiDOM package called `apidom-ns-openapi-2`](https://github.com/swagger-api/apidom/pull/3218)
- [x] implement refractor layer ([current progress here](https://github.com/swagger-api/apidom/tree/main/packages/apidom-ns-openapi-2#implementation-progress))
- [x] [prepare for initial release](https://github.com/swagger-api/apidom/pull/3314)
- [x] [add replace-empty-element refractor plugin](https://github.com/swagger-api/apidom/pull/3315)
- [x] [release](https://github.com/swagger-api/apidom/releases/tag/v0.79.0)
