### ISSUE TITLE
OpenAPI 2.0 - dereference strategy in apidom-reference

### ISSUE THREAD

**Issue by char0n** [swagger-api/apidom#3102]
The goal of this issue is to create a dereference strategy for OpenAPI 2.0 in apidom-reference package.

**TODO**:
- [x] OpenAPI 2.0 dereference strategy
- [x] tests for Reference Object 
- [x] tests for Path Item Object
- [x] tests for JSON Reference Object
- [x] location tests
