### ISSUE TITLE
Implement snapshot testing for ApiDOM namespaces

### ISSUE THREAD

**Issue by char0n** [swagger-api/apidom#360]
The most appropriate way of testing ApiDOM namespaces seems to be snapshot testing. We need to implement it as a basic testing mechanism for regression detection in namespace packages.

**TODO:**

- [x] [Implement support for serializing ApiDOM into S-Expression](https://github.com/swagger-api/apidom/issues/429)
- [x] [Implement support for snapshot testing in ApiDOM](https://github.com/swagger-api/apidom/issues/432)
- [ ] [OpenApi 3.1.0 namespace snapshot tests](https://github.com/swagger-api/apidom/issues/438)
- [x] [AsyncApi 2.0.0 namespace snapshot tests](https://github.com/swagger-api/apidom/issues/434)
