### ISSUE TITLE
apidom-reference: regression in AsyncAPI 2.x dereferencing

### ISSUE THREAD

**Issue by char0n** [swagger-api/apidom#3974]
**TODO**:

- [x] [address regression in AsyncAPI 2.x](https://github.com/swagger-api/apidom/pull/3975)
- [x] [address regression in OpenAPI 2.0](https://github.com/swagger-api/apidom/pull/3976)
- [x] [address regression in OpenAPI 3.0](https://github.com/swagger-api/apidom/pull/3977)
- [x] [address regression in OpenAPI 3.1](https://github.com/swagger-api/apidom/pull/3978)

---

### Steps To Reproduce

Given the following AsyncAPI definition:
```yaml
asyncapi: '2.4.0'
info:
  title: Base API
  version: '1.0.0'
  description: ""
channels:
  c:
    publish:
      message:
        $ref: 'https://test-fake-url.com/apis/test/1#/components/messages/someMessage'
```

With https://test-fake-url.com/apis/test/1 linking to this file:
```yaml
asyncapi: '2.4.0'
info:
  title: Components
  version: '1.0.0'
  description: ""

components:
  messages:
    someMessage:
      contentType: application/json
      payload:
        $ref: "#/components/schemas/somePayload"
  schemas:
    somePayload:
      type: object
      properties:
        sentAt:
          $ref: "#/components/schemas/sentAt"
    sentAt:
      type: string
      format: date-time
      description: Date and time when the message was sent.
```

When calling dereference, up to now we would have gotten back the following (no $refs, everything fully inlined)

```yaml
"asyncapi": "2.4.0"
"info":
  "title": "Base API"
  "version": "1.0.0"
  "description": ""
"channels":
  "c":
    "publish":
      "message":
        "contentType": "application/json"
        "payload":
          "type": "object"
          "properties":
            "sentAt":
              "type": "string"
              "format": "date-time"
              "description": "Date and time when the message was sent."
```
However, now we get we get the following ($ref to sentAt) which causes additional problems as the local definition for sentAt is not present

```yaml
"asyncapi": "2.4.0"
"info":
  "title": "Base API"
  "version": "1.0.0"
  "description": ""
"channels":
  "c":
    "publish":
      "message":
        "contentType": "application/json"
        "payload":
          "type": "object"
          "properties":
            "sentAt":
              "$ref": "#/components/schemas/sentAt"
```

**Comment by char0n** [comment]
I could successfully reproduce.

**Comment by char0n** [comment]
The issue is related to refractor cache. 

The workaround for now is to perform dereference in `replace` or `error` mode:

```js
const actual = await dereference(<PATH>, {
  parse: { mediaType: mediaTypes.latest('json') },
  dereference: { circular: 'error' },
});
```

**Comment by char0n** [comment]
Bug fix needs to applied to all dereferencing strategies.

**Comment by char0n** [comment]
All dereference strategies has been fixed.
