### ISSUE TITLE
Complete Dereference for OpenApi 3.1

### ISSUE THREAD

**Issue by char0n** [swagger-api/apidom#425]
We already have dereference implementation for Reference And Schema Objects. Additional usecases that are not covered in current implementation needs to be implemented and new tests covering various usecases must be introduced.

- [x] test coverage for different spec. objects
- [x] [dereference of Path Item Object](https://github.com/swagger-api/apidom/issues/458)
- [x] [dereference of Link Object](https://github.com/swagger-api/apidom/issues/463)
- [x] [dereference of Example.externalValue field](https://github.com/swagger-api/apidom/issues/467)
- [ ] all specification objects that can be referenced must allow to enumerate their `description` or `summary` property ([example](https://github.com/swagger-api/apidom/blob/2b3b69fc5f51bc1b3c05026ad7a31c9661d2fca1/apidom/packages/apidom-ns-openapi-3-1/src/elements/Parameter.ts#L108)), Schema Object needs to be reviewed as well
- [ ] tests for Schema Object indirections
