### ISSUE TITLE
Complete External Resolution for OpenApi 3.1

### ISSUE THREAD

**Issue by char0n** [swagger-api/apidom#426]
We already have external resolutino implementation for Reference And Schema Objects. Additional usecases that are not covered in current implementation needs to be implemented and new tests covering various usecases must be introduced.

- [x] [external resolution of Path Item Object](https://github.com/swagger-api/apidom/issues/459)
- [x] [external resolution of Link Object](https://github.com/swagger-api/apidom/issues/465) 
- [x] [external resolution of Example Object `externalValue`](https://github.com/swagger-api/apidom/issues/467)
