### ISSUE TITLE
Switch `moduleResolution` in tsconfig to `nodenext`

### ISSUE THREAD

**Issue by char0n** [swagger-api/apidom#4385]
This will allow TypeScript to recognize `exports` field in npm packages. Without this setting on we're not able to use proper imports of sub-paths with appropriate typings. `nodenext` this setting will also require to have an explicit file extensions, which will require a lot of changes to a lot of files.

### TODO

This list is for the case when all packages has been transformed.

- [x] Global `tsconfig.json` needs to be modified when all packages are transformed
- [x] Local `tsconfig.json` needs to be amended to original form
- [x] Local `.eslintrc` needs to be dropped and made global
- [x] [Convert packages tests to nodenext as well](https://github.com/swagger-api/apidom/pull/4446#issuecomment-2461791531)

**Comment by char0n** [comment]
In https://github.com/swagger-api/apidom/pull/4402, I've figured out how to migrate progressively monorepo package by package and transformed the `apidom-error` package.

**Comment by char0n** [comment]
This ticket has been completed. Some packages run their tests still in legacy mode, due to the dependencies they are using.
