### ISSUE TITLE
ApiDOM Playground - enhancements

### ISSUE THREAD

**Issue by char0n** [swagger-api/apidom#476]
The demo is comming and we need to get ApiDOM Playground into fully workable state. 

**Todo**:
- [x] OAS 3.1: all current features needs to work seamlessly
- [x] AsyncApi 2.0: all current features needs to work seamlessly
- [x] resolving and dereferencing should only be enabled if baseURI is provided
- [x] S-expression interpretation should be added
