### ISSUE TITLE
Migrate monorepo to npm@7 and integrate workspaces with lerna

### ISSUE THREAD

**Issue by char0n** [swagger-api/apidom#483]
https://github.blog/2020-10-13-presenting-v7-0-0-of-the-npm-cli/

We have full documentation of lerna process within current monorepo setup. These processes will change with npm@7, so documentation needs to be amended. Part of this issue is also updating [Lerna](https://www.npmjs.com/package/lerna) to latest version.

**Resources**:

- https://github.com/npm/rfcs/blob/latest/implemented/0026-workspaces.md
- https://github.com/npm/rfcs/blob/latest/implemented/0025-install-peer-deps.md
- https://betterprogramming.pub/the-step-by-step-guide-to-understanding-and-adopting-npm-7-914504f7090f
- https://betterprogramming.pub/package-jsons-dependencies-in-depth-a1f0637a3129
- https://blog.npmjs.org/post/621733939456933888/npm-v7-series-why-keep-package-lockjson
- https://2ality.com/2021/07/simple-monorepos.html
- https://oliverjam.es/blog/npm-workspaces/

**Tasks**:

- [x] Integrate npm@7 workspaces with Lerna
- [x] update Lerna to latest version
- [x] update dev deps of the Monorepo
- [x] update deps of individual packages
- [x] update eslint/prettier/typescript realated deps (will require code modifications)
- [x] check if security audit is reporting correctly

**Notes**: 

 - min node and npm version change
 - packageLock version 2
 - removed link-parent-bin
 - no dependencies entry in root package / replaced by workspaces
 - devDependencies in packages gets installed
 - no common dev dependencies
 - replace common scripts with workspaces option (didn't work npm is not aware of the package topology)
