### ISSUE TITLE
Convert monorepo to ESM

### ISSUE THREAD

**Issue by char0n** [swagger-api/apidom#930]
Backward compatibility with CommonJS needs to be achieved. This change will allow us to consume new modern pure ESM npm packages along will legacy CommonJS ones. The methodology will be to transform one package at a time using trunk based development practices (if possible).

**TODO:**

- [x] apidom
- [x] apidom-ast
- [x] apidom-core
- [x] apidom-ns-asyncapi-2
- [x] apidom-ns-openapi-3-1
- [x] apidom-parser
- [x] apidom-parser-adapter-asyncapi-json-2
- [x] apidom-parser-adapter-asyncapi-yaml-2
- [x] apidom-parser-adapter-openapi-json-3-1
- [x] apidom-parser-adapter-openapi-yaml-3-1
- [x] apidom-parser-adapter-json
- [x] apidom-parser-adapter-yaml-1-2
- [x] apidom-reference
- [x] apidom-ls
- [x] check playground build
- [x] check eslint ignore files
- [x] babel env: cjs-new to cjs
- [x] transform perf files
- [x] rebuild repo locally
- [x] run nightly build that checks everything
- [x] create issue for - reconsider submodules for exports in ApiDOM
- [x] release new ApiDOM release

**Resources**:
- https://nodejs.org/docs/latest-v16.x/api/esm.html
- https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
- https://nodejs.org/docs/latest-v16.x/api/packages.html
