### ISSUE TITLE
ApiDOM plan for going public

### ISSUE THREAD

**Issue by char0n** [swagger-api/apidom#956]
We can divide requirements for ApiDOM repo going public into two categories: **Required** and **Nice To Have**. Each item in Required and Nice To Have categories will be converted to separate track-able issue. If additional items are identified during the work, these new items must be categorized in one of the identified categories and converted to issues.

### Required

Items in this category are necessary to be implemented for ApiDOM monorepo going public. Item are ordered by priority in descending order.

- [x] Make sure our issues don't disclose any privileged information 
- [ ] [Main Usage examples in top level README file](https://github.com/swagger-api/apidom/issues/985)
- [x] Installation instructions
- [x] README header in apidom-ls about unstable phase
- [x] Switch repository from private to public
- [x] ApiDOM Playground URL

### Nice to have

Items in this category are not necessary for this repo to go public, but it would be nice to have them processed before going public. Items are ordered by priority in descending order.

- [ ] [Create facade entry point package](https://github.com/swagger-api/apidom/issues/983)
- [ ] [Rename all the packages to use @swagger scope](https://github.com/swagger-api/apidom/issues/986)
- [ ] [Release @swagger/* packages to npmjs.org repository](https://github.com/swagger-api/apidom/issues/987)
- [x] Fix typos in main README file
- [ ] [Set repo description, website, topics](https://github.com/swagger-api/apidom/issues/791)
- [ ] [Set GitHub Repo Insights](https://github.com/swagger-api/apidom/issues/988)
- [ ] [Use @babel/plugin-transform-runtime](https://github.com/swagger-api/apidom/issues/47)
- [ ] [Define minimum Node.js version and Browser list](https://github.com/swagger-api/apidom/issues/989)
- [ ] [Regenerate package-lock.json automatically after release](https://github.com/swagger-api/apidom/issues/931)
- [ ] [Analyze UMD bundles](https://github.com/swagger-api/apidom/issues/696)
- [ ] [Convert monorepo packages to ESM with backward compatibility](https://github.com/swagger-api/apidom/issues/930)
- [ ] [Set branch protection rules](https://github.com/swagger-api/apidom/issues/929)

**Comment by char0n** [comment]
Closing this as this issue has been replaced with epic `Release ApiDOM to open source`
